### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by anbenson**

### CODE REVIEW

**Comment by tsipinakis** [comment]
>  @tsipinakis will do the merge, as he has got access to the server.

I don't actually, the website is hosted on github pages with a stop to @knopwob's server on the way to add SSL. All I do is merge and run a local script to push to the `gh-pages` branch ;)

**Comment by bebehei** [comment]
> local script

Could you please share it with me?

**Comment by tsipinakis** [comment]
```
hugo
COMMIT="$(git rev-parse HEAD | cut -b1-7)"
cd public/
git add -A
git commit -m "Deploy $COMMIT"
```

It assumes that you have a second git repo in public/ cloned to the gh-pages branch (terrible hack I know, but it works)

**Comment by bebehei** [comment]
@knopwob @tsipinakis I think we can simplify the chain even more: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Pull request merged**
