### PR TITLE
Remove warnings from example config

### PR DESCRIPTION
**Pull request by burik666**
```
Warning: 'allow_markup' is deprecated, please use 'markup' instead.
Warning: The frame section is deprecated, width has been renamed to frame_width and moved to the global section.
Warning: The frame section is deprecated, color has been renamed to frame_color and moved to the global section.
```

### CODE REVIEW

**Comment by bebehei** [comment]
Due tue proper review support on my mobile it's "Approved" via comment. @tsipinakis will merge it.

Please also fire the corresponding PR on our main dunst repo, too. There is also a default dunstrc file. Thanks in advance.

**Comment by burik666** [comment]
@bebehei, the dunstrc is correct in the main repo.

**Comment by bebehei** [comment]
@burik: Well, then it's a much better catch. :grinning:

**Comment by tsipinakis** [comment]
Thanks! The website doesn't usually get much love from contributors.

**Pull request merged**
